MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.6
    BG_IOU_THRESHOLD: 0.6
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractorNeighbor"
    PREDICTOR: "FPNPredictorNeighbor"
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.00125
  WEIGHT_DECAY: 0.0001
  STEPS: (960000, 1280000)
  # MAX_ITER: 1440000
  MAX_ITER: 200
  IMS_PER_BATCH: 1
  # BASE_LR: 0.02
  # WEIGHT_DECAY: 0.0001
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
TEST:
  IMS_PER_BATCH: 1 


